version: '3.1'

services:

  mediawiki:
    image: gcr.io/wbstack/mediawiki:1.33-b0.5-c0.8-e0.38
    volumes:
      - ./doMaintenance.php:/var/www/html/maintenance/doMaintenance.php
      - ./wikWikiInfoDefaults-clean.json:/var/www/html/wikWikiInfoDefaults.json
      - ./wikWikiInfoDefaults.php:/var/www/html/wikWikiInfoDefaults.php
    environment:
      WIKWIKI_INFO_FROM: defaults-file
    links:
    - sql-clean
  sql-clean:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wiki
    networks:
      default:
        aliases:
        - mediawiki-sql
  sql-admin:
    image: adminer:4.6
    ports:
    - 1234:8080
