version: '3.1'

services:

  mediawiki:
    image: gcr.io/wbstack/mediawiki:1.34-7.3-b0.1-c0.1-e0.2
    volumes:
      - ./maintWikWiki.json:/var/www/html/w/maintWikWiki.json
    environment:
      WIKWIKI_INFO_FROM: defaults-file
    links:
    - sql-clean
  sql-clean:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wiki
    networks:
      default:
        aliases:
        - mediawiki-sql
  sql-admin:
    image: adminer:4.6
    ports:
    - 1234:8080
