version: '3.1'

services:

  mediawiki:
    image: gcr.io/wbstack/mediawiki:1.34-7.3-b0.1-c0.1-e0.2
    volumes:
      - ./maintWikWiki.json:/var/www/html/w/maintWikWiki.json
#      - ./LocalSettings.php:/var/www/html/w/LocalSettings.php
    environment:
      MW_DB_SERVER_MASTER: mediawiki-sql
      MW_DB_SERVER_SLAVE: mediawiki-sql
      MW_EMAIL_DOMAIN: foo
      MW_REDIS_SERVER: foo
      MW_MAILGUN_API_KEY: foo
      MW_MAILGUN_DOMAIN: foo
      MW_RECAPTCHA_SITEKEY: foo
      MW_RECAPTCHA_SECRETKEY: foo
      PLATFORM_API_BACKEND_HOST: foo
    links:
    - sql-upgrade
  sql-upgrade:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wiki
    volumes:
    - ./upgradeFrom.sql:/docker-entrypoint-initdb.d/01_upgradeFrom.sql
    networks:
      default:
        aliases:
         - mediawiki-sql
  sql-admin:
    image: adminer:4.6
    ports:
    - 1234:8080
