version: '3.1'

services:

  mediawiki-clean:
    image: wikwiki-mediawiki:1.31
    links:
    - sql-clean
  mediawiki-upgrade:
    image: wikwiki-mediawiki:1.31
    links:
    - sql-upgrade
  sql-clean:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wiki
  sql-upgrade:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wiki
    volumes:
    - ./upgradeFrom.sql:/docker-entrypoint-initdb.d/01_upgradeFrom.sql
  sql-admin:
    image: adminer:4.6
    ports:
    - 1234:8080
